# fly.toml app configuration file generated for daikin-extract-secret-key on 2025-01-21T13:36:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'daikin-extract-secret-key'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
